# Exception Handling

# try to comment this out and run the code!
# ------------------
x = "Hello World!"
# ------------------

try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")